# Generated by Django 6.0.7 on 2026-07-13 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('delayed', 'Delayed'), ('recalled', 'Recalled')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('temp_name', models.CharField(max_length=200)),
                ('subj', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('reminder', 'Reminder'), ('discount', 'Discount'), ('shipment_delay', 'Shipment Delay')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AIPromptHistory',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('generated_output', models.TextField()),
                ('llm_used', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('tool_used', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('cam_id', models.AutoField(primary_key=True, serialize=False)),
                ('cap_name', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('subj', models.CharField(max_length=255)),
                ('mail_body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='core.template')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=200)),
                ('contactname', models.CharField(max_length=100)),
                ('c_mail', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('customer_type', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver')], max_length=20)),
                ('comp_type', models.CharField(choices=[('distributor', 'Distributor'), ('hospital', 'Hospital'), ('retail', 'Retail')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('del_status', models.CharField(default='Pending', max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('replied', models.BooleanField(default=False)),
                ('cam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.campaign')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('agenda', models.TextField()),
                ('meeting_date', models.DateField()),
                ('meeting_time', models.TimeField()),
                ('google_event_id', models.CharField(max_length=255, unique=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('mp_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.client')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('sales', 'Sales')], default='sales', max_length=20)),
                ('auth_provider', models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('linkedin', 'LinkedIn')], default='local', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
